include:
  - project: 'atari/bundle-ci'
    file: '/bundle-ci.yml'
    ref: 'main'

build:
  script:
    - mkdir build
    - cd build
    - make-bundle.sh ../native-indy800-example.yaml
    - mv *.bundle native-indy800-example.log ..
